#!/usr/bin/env python3

import os
import sys

folder = sys.argv[1]

dir_path = f'./{folder}'
# wallpaper_pack_name = 'msm-wallpaper'


# f = open(f"{wallpaper_pack_name}.xml", "w")
f = open(f"{folder}.xml", "w")

f.write("""<?xml version="1.0"?>
<!DOCTYPE wallpapers SYSTEM "gnome-wp-list.dtd">
<wallpapers>
        """)

for path in os.listdir(dir_path):
	print(path)
	filename = os.path.splitext(path)[0]
 
	f.write(f"""
    <wallpaper deleted="false">
		<name>{filename}</name>
		<filename>/usr/share/backgrounds/{folder}/{path}</filename>
		<options>zoom</options>
		<shade_type>solid</shade_type>
		<pcolor>#212121</pcolor>
		<scolor>#000000</scolor>
	</wallpaper>""")
 
 
f.write("\n</wallpapers>")

print("\n\n\n[COMPLETED] Script has completed running!")